"""
Django settings for mamefoods project.

Generated by 'django-admin startproject' using Django 5.0.6.

Modified for local development.
"""
import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-p5gr-x0d3+w43#*2xx%)8@!l39t3a05l&_44zhkhz)h)vz+4(^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'mamefoods.com', 'www.mamefoods.com']


# Application definition

INSTALLED_APPS = [
    # 'unfold',                     # Admin theme you're using
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'main.apps.MainConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mamefoods.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'main.context_processors.site_config',
            ],
        },
    },
]

WSGI_APPLICATION = 'mamefoods.wsgi.application'


# Database – switched to a local SQLite file
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'mamefood_db',
        'USER': 'mamefood_db',
        'PASSWORD': 'FWnzU]1Fa;mz',
        'HOST': 'localhost',
        'PORT': '3306',
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}

# No longer need pymysql for SQLite
import pymysql
pymysql.install_as_MySQLdb()


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'  
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ---------- Unfold admin config (uncomment and adjust if needed) ----------
# from django.templatetags.static import static
# UNFOLD = {
#     "SITE_TITLE": "MAMEFOODS Admin",
#     "SITE_HEADER": "MAMEFOODS",
#     "SITE_URL": "/",
#     "SITE_ICON": lambda request: static("img/logo.png"),
#     "SITE_LOGO": lambda request: static("img/logo.png"),
#     "COLORS": {
#         "primary": {
#             "50": "250 245 255",
#             "100": "243 232 255",
#             "200": "233 213 255",
#             "300": "216 180 254",
#             "400": "192 132 252",
#             "500": "168 85 247",
#             "600": "147 51 234",
#             "700": "126 34 206",
#             "800": "107 33 168",
#             "900": "88 28 135",
#             "950": "59 7 100",
#         },
#     },
#     "SIDEBAR": {
#         "show_search": True,
#         "show_all_applications": True,
#         "navigation": [
#             {"title": "Dashboard", "icon": "dashboard", "link": "/admin"},
#             {
#                 "title": "Products",
#                 "icon": "shopping_bag",
#                 "links": [
#                     {"title": "Categories", "link": "/admin/main/productcategory/"},
#                     {"title": "Products", "link": "/admin/main/product/"},
#                     {"title": "Variants", "link": "/admin/main/productvariant/"},
#                     {"title": "Images", "link": "/admin/main/productimage/"},
#                 ],
#             },
#             {"title": "Team", "icon": "people", "link": "/admin/main/teammember/"},
#             {"title": "Certifications", "icon": "verified", "link": "/admin/main/certification/"},
#             {"title": "Messages", "icon": "email", "link": "/admin/main/contactmessage/"},
#         ],
#     },
# }