# Generated by Django 5.2.3 on 2026-04-28 20:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='certifications/')),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('icon_class', models.CharField(default='bx bxs-leaf', help_text="Icon class from Boxicons (e.g. 'bx bxs-leaf')", max_length=50)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Product Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='MAME Foods', max_length=100)),
                ('hero_slide1_title', models.CharField(blank=True, default='Welcome to MAME Foods', max_length=200)),
                ('hero_slide1_subtitle', models.TextField(blank=True, default="Producer of Malawi's finest aromatic long grain rice, flour, and agricultural products")),
                ('hero_slide1_image', models.ImageField(blank=True, help_text='Leave empty to use static fallback (img/slide/slide-1.jpg)', null=True, upload_to='hero/')),
                ('hero_slide1_button_text', models.CharField(blank=True, default='Discover More', max_length=50)),
                ('hero_slide1_button_link', models.CharField(blank=True, default='#about-us', max_length=200)),
                ('hero_slide2_title', models.CharField(blank=True, default='Organic & Authentic Taste', max_length=200)),
                ('hero_slide2_subtitle', models.TextField(blank=True, default='Experience the original "kumudzi" taste in every product we create')),
                ('hero_slide2_image', models.ImageField(blank=True, null=True, upload_to='hero/')),
                ('hero_slide2_button_text', models.CharField(blank=True, default='Our Products', max_length=50)),
                ('hero_slide2_button_link', models.CharField(blank=True, default='#products', max_length=200)),
                ('hero_slide3_title', models.CharField(blank=True, default='Quality Certified', max_length=200)),
                ('hero_slide3_subtitle', models.TextField(blank=True, default='Pre-certified by Malawi Bureau of Standards with full certification underway')),
                ('hero_slide3_image', models.ImageField(blank=True, null=True, upload_to='hero/')),
                ('hero_slide3_button_text', models.CharField(blank=True, default='Our Certifications', max_length=50)),
                ('hero_slide3_button_link', models.CharField(blank=True, default='#certifications', max_length=200)),
                ('about_title', models.CharField(blank=True, default='About MAME Foods', max_length=200)),
                ('about_subtitle', models.CharField(blank=True, default='Trusted indigenous brand providing authentic "kumudzi" taste', max_length=200)),
                ('about_description', models.TextField(blank=True, default='MAME Foods is a producer and supplier of food stuffs in Malawi...')),
                ('about_bullet1', models.CharField(blank=True, default='Our rice is pre-certified by the Malawi Bureau of Standards', max_length=200)),
                ('about_bullet2', models.CharField(blank=True, default='Substantial progress towards full certification', max_length=200)),
                ('about_bullet3', models.CharField(blank=True, default='All products in different phases of certification process', max_length=200)),
                ('about_closing', models.TextField(blank=True, default='Our drive is to give you quality organic food stuffs that maintain their original "kumudzi" taste at a good price.')),
                ('show_about_section', models.BooleanField(default=True)),
                ('show_products_section', models.BooleanField(default=True)),
                ('show_certifications_section', models.BooleanField(default=True)),
                ('products_section_title', models.CharField(blank=True, default='Our Products', max_length=200)),
                ('products_section_subtitle', models.CharField(blank=True, default='Premium quality food products made with care', max_length=200)),
                ('certifications_section_title', models.CharField(blank=True, default='Our Certifications', max_length=200)),
                ('certifications_section_subtitle', models.CharField(blank=True, default='Quality assurance and standards compliance', max_length=200)),
                ('contact_address_line1', models.CharField(blank=True, default='MAME House', max_length=200)),
                ('contact_address_line2', models.CharField(blank=True, default='Plot 10/069, Luther Street', max_length=200)),
                ('contact_city', models.CharField(blank=True, default='Area 10, Lilongwe', max_length=100)),
                ('contact_postal', models.CharField(blank=True, default='P.O. Box 30632, Capital City, Lilongwe 3', max_length=100)),
                ('contact_phone1', models.CharField(blank=True, default='+265 999 950 489', max_length=20)),
                ('contact_phone2', models.CharField(blank=True, max_length=20)),
                ('contact_email1', models.EmailField(blank=True, default='info@mamefoods.mw', max_length=254)),
                ('contact_email2', models.EmailField(blank=True, max_length=254)),
                ('google_maps_embed_url', models.URLField(blank=True, default='https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3770.755798307342!2d33.76824441490085!3d-13.983324959861402!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2zMTPCsDU4JzU5LjkiUyAzM8KwNDYnMTUuNSJF!5e0!3m2!1sen!2smw!4v1651234567890!5m2!1sen!2smw', max_length=1000)),
                ('whatsapp_number', models.CharField(blank=True, help_text='Full international number, e.g. +265999950489', max_length=20)),
                ('whatsapp_message', models.TextField(blank=True, default="Hello MAME Foods! I'd like to know more about your products.")),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('footer_developer_text', models.CharField(default='Developed by Pritech', help_text='Appears in the copyright line', max_length=200)),
                ('footer_developer_url', models.URLField(blank=True, help_text='Optional link for the developer')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='team/')),
                ('twitter', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('detailed_description', models.TextField(blank=True)),
                ('certification_status', models.CharField(choices=[('pre', 'Pre-Certified'), ('full', 'Fully Certified'), ('in_progress', 'In Progress'), ('not_applicable', 'Not Applicable')], default='in_progress', max_length=20)),
                ('is_organic', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='main.productcategory')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.product')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('weight', models.CharField(blank=True, help_text='e.g., 1kg, 5kg, 10kg', max_length=50)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/variants/')),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('sku', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_variants', to='main.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='variants',
            field=models.ManyToManyField(blank=True, related_name='main_products', to='main.productvariant'),
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('content', models.TextField()),
                ('excerpt', models.TextField(blank=True)),
                ('featured_image', models.ImageField(upload_to='blog/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(to='main.category')),
                ('tags', models.ManyToManyField(to='main.tag')),
            ],
        ),
    ]
